-- =============================================================================
-- Pet Project API — initial database schema
-- PostgreSQL 14+
--
-- Usage (local or server):
--   psql "$DATABASE_URL" -f src/migrations/001_initial_schema.sql
--
-- Or:
--   psql -h HOST -U USER -d DBNAME -f src/migrations/001_initial_schema.sql
--
-- All primary keys are UUID (GUID), generated by gen_random_uuid().
-- Safe to re-run: uses IF NOT EXISTS where applicable.
-- =============================================================================

BEGIN;

-- UUID generation (preferred over uuid-ossp on modern PostgreSQL)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    name          VARCHAR(100) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(64),
    avatar_url    TEXT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_email UNIQUE (email)
);

COMMENT ON TABLE users IS 'Application accounts';
COMMENT ON COLUMN users.password_hash IS 'SHA-256 hex hash from client';

-- ---------------------------------------------------------------------------
-- families
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS families (
    id         UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    name       VARCHAR(100) NOT NULL,
    owner_id   UUID         NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_families_owner UNIQUE (owner_id)
);

COMMENT ON TABLE families IS 'Family group; one owner per family';

-- ---------------------------------------------------------------------------
-- family_members (one user — one family)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS family_members (
    id           UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id    UUID         NOT NULL REFERENCES families (id) ON DELETE CASCADE,
    user_id      UUID         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    display_name VARCHAR(100) NOT NULL,
    initials     VARCHAR(4)   NOT NULL,
    subtitle     VARCHAR(255),
    description  TEXT,
    gradient     VARCHAR(10)  NOT NULL DEFAULT 'base',
    role         VARCHAR(20)  NOT NULL DEFAULT 'member',
    legacy_key   VARCHAR(50),
    joined_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_family_members_user UNIQUE (user_id),
    CONSTRAINT uq_family_members_pair UNIQUE (family_id, user_id),
    CONSTRAINT chk_family_members_role CHECK (role IN ('owner', 'member')),
    CONSTRAINT chk_family_members_gradient CHECK (gradient IN ('base', 'alt'))
);

COMMENT ON TABLE family_members IS 'User membership and display profile inside a family';

-- ---------------------------------------------------------------------------
-- family_invites (phase 2 — optional, created upfront)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS family_invites (
    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id  UUID        NOT NULL REFERENCES families (id) ON DELETE CASCADE,
    code       VARCHAR(12) NOT NULL,
    created_by UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_by    UUID        REFERENCES users (id) ON DELETE SET NULL,
    used_at    TIMESTAMPTZ,
    CONSTRAINT uq_family_invites_code UNIQUE (code)
);

COMMENT ON TABLE family_invites IS 'Invite codes to join a family';

-- ---------------------------------------------------------------------------
-- goals (shared family goals)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS goals (
    id           UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id    UUID         NOT NULL REFERENCES families (id) ON DELETE CASCADE,
    title        VARCHAR(255) NOT NULL,
    short        TEXT,
    category     VARCHAR(50),
    horizon      VARCHAR(50),
    status       VARCHAR(50)  NOT NULL DEFAULT 'В начале',
    owners_label VARCHAR(100) NOT NULL DEFAULT 'Вся семья',
    progress     SMALLINT     NOT NULL DEFAULT 0,
    cover_image  TEXT,
    cover_alt    VARCHAR(255),
    hero_image   TEXT,
    hero_alt     VARCHAR(255),
    feeling      TEXT,
    legacy_key   VARCHAR(50),
    created_by   UUID         REFERENCES users (id) ON DELETE SET NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_goals_progress CHECK (progress BETWEEN 0 AND 100)
);

COMMENT ON TABLE goals IS 'Shared family goals (wish map)';

-- ---------------------------------------------------------------------------
-- goal_images (gallery)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS goal_images (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    goal_id    UUID NOT NULL REFERENCES goals (id) ON DELETE CASCADE,
    src        TEXT NOT NULL,
    alt        VARCHAR(255),
    sort_order INT  NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- goal_steps
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS goal_steps (
    id         UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    goal_id    UUID         NOT NULL REFERENCES goals (id) ON DELETE CASCADE,
    text       VARCHAR(500) NOT NULL,
    sort_order INT          NOT NULL DEFAULT 0,
    is_done    BOOLEAN      NOT NULL DEFAULT false
);

-- ---------------------------------------------------------------------------
-- goal_tags
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS goal_tags (
    id      UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    goal_id UUID        NOT NULL REFERENCES goals (id) ON DELETE CASCADE,
    tag     VARCHAR(50) NOT NULL
);

-- ---------------------------------------------------------------------------
-- goal_description_blocks
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS goal_description_blocks (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    goal_id    UUID NOT NULL REFERENCES goals (id) ON DELETE CASCADE,
    text       TEXT NOT NULL,
    sort_order INT  NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- wishes (personal and family-visible wishlist items)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS wishes (
    id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    family_id   UUID         REFERENCES families (id) ON DELETE SET NULL,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    category    VARCHAR(50),
    budget      VARCHAR(50),
    link        TEXT,
    image       TEXT,
    alt         VARCHAR(255),
    legacy_key  VARCHAR(50),
    status      VARCHAR(20)  NOT NULL DEFAULT 'wanted',
    reserved_by UUID         REFERENCES users (id) ON DELETE SET NULL,
    reserved_at TIMESTAMPTZ,
    visibility  VARCHAR(20)  NOT NULL DEFAULT 'family',
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_wishes_status CHECK (status IN ('wanted', 'reserved', 'purchased')),
    CONSTRAINT chk_wishes_visibility CHECK (visibility IN ('private', 'family'))
);

COMMENT ON TABLE wishes IS 'Wishlist items; visibility private = my wishes, family = shared list';

-- ---------------------------------------------------------------------------
-- indexes
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_family_members_family ON family_members (family_id);
CREATE INDEX IF NOT EXISTS idx_family_invites_family ON family_invites (family_id);
CREATE INDEX IF NOT EXISTS idx_goals_family ON goals (family_id);
CREATE INDEX IF NOT EXISTS idx_goal_images_goal ON goal_images (goal_id);
CREATE INDEX IF NOT EXISTS idx_goal_steps_goal ON goal_steps (goal_id);
CREATE INDEX IF NOT EXISTS idx_goal_tags_goal ON goal_tags (goal_id);
CREATE INDEX IF NOT EXISTS idx_goal_description_blocks_goal ON goal_description_blocks (goal_id);
CREATE INDEX IF NOT EXISTS idx_wishes_user ON wishes (user_id);
CREATE INDEX IF NOT EXISTS idx_wishes_family ON wishes (family_id);
CREATE INDEX IF NOT EXISTS idx_wishes_status ON wishes (status);

-- ---------------------------------------------------------------------------
-- updated_at trigger (optional helper for all tables with updated_at)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
    t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['users', 'families', 'goals', 'wishes']
    LOOP
        EXECUTE format(
            'DROP TRIGGER IF EXISTS trg_%s_updated_at ON %I;
             CREATE TRIGGER trg_%s_updated_at
             BEFORE UPDATE ON %I
             FOR EACH ROW EXECUTE PROCEDURE set_updated_at();',
            t, t, t, t
        );
    END LOOP;
END;
$$;

COMMIT;
